### ISSUE TITLE
Issue with link generation - Error with redrawlines linkselection

### ISSUE THREAD

**Issue by kenisteward** [swimlane/ngx-graph#41]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Recieve linkselection.attr().transition is not a function due to d3 upgrades
![transition](https://user-images.githubusercontent.com/12831669/33399946-511dd3c8-d522-11e7-8bb8-aaef73f12bf8.PNG)

**Expected behavior**
no error

**Reproduction of the problem**
https://stackblitz.com/edit/angular-vtavqy

this doesn't show the error but it is definitely not building / showing the edges.  In my personal case i get the error

**Please tell us about your environment:**
defined in the stackblitz

**Comment by kenisteward** [comment]
Possible fix

add 

import {transition} from 'd3-transition';

**Comment by isaacplmann** [comment]
It looks like you're getting pretty close to a solution.  Want to submit a PR?

**Comment by kenisteward** [comment]
sure!!!!

**Comment by kenisteward** [comment]
see #43

**Comment by kenisteward** [comment]
resolved with #43

**Comment by Wu-Li** [comment]
I'm still getting this error today with the latest version, even if I include d3-transition (or just d3).
![ngx-error](https://github.com/swimlane/ngx-graph/assets/920332/340e0b0f-e68c-467d-990a-b52a72cbdaef)
Haven't done hardly anything with it, just copied the quick start demo HTML from the docs to test that the newly installed package is working.

**Comment by WograTimKoehler** [comment]
@Wu-Li   
I don't know if you already found the solution, but as it is mentioned in [this issue](https://github.com/swimlane/ngx-graph/issues/487), it is a problem with the versioning. You can fix it by adding 
```json
  "overrides": {
    "d3-selection": "3.0.0"
  },
```
to your package.json

**Comment by Wu-Li** [comment]
That worked, thank you!

**Comment by divyrathoreimpetus** [comment]
@kenisteward , is this fix available in 8.2.3. I'm facing this issue there.

**Comment by wangruoni** [comment]
same... 8.2.3. still facing the issue

**Comment by mordecai-git** [comment]
T

> @Wu-Li I don't know if you already found the solution, but as it is mentioned in [this issue](https://github.com/swimlane/ngx-graph/issues/487), it is a problem with the versioning. You can fix it by adding
> 
> ```json
>   "overrides": {
>     "d3-selection": "3.0.0"
>   },
> ```
> 
> to your package.json

This worked for me in version 8.4.0
